using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace AoE2NetDesktop.AoE2DE.Tests
{
    [TestClass()]
    public class CountryCodeTests
    {
        [TestMethod()]
        [DataRow("AD", "Andorra")]
        [DataRow("AE", "United Arab Emirates")]
        [DataRow("AF", "Afghanistan")]
        [DataRow("AG", "Antigua and Barbuda")]
        [DataRow("AI", "Anguilla")]
        [DataRow("AL", "Albania")]
        [DataRow("AM", "Armenia")]
        [DataRow("AN", "Netherlands Antilles")]
        [DataRow("AO", "Angola")]
        [DataRow("AQ", "Antarctica")]
        [DataRow("AR", "Argentina")]
        [DataRow("AS", "American Samoa")]
        [DataRow("AT", "Austria")]
        [DataRow("AU", "Australia")]
        [DataRow("AW", "Aruba")]
        [DataRow("AZ", "Azerbaijan")]
        [DataRow("BA", "Bosnia and Herzegovina")]
        [DataRow("BB", "Barbados")]
        [DataRow("BD", "Bangladesh")]
        [DataRow("BE", "Belgium")]
        [DataRow("BF", "Burkina Faso")]
        [DataRow("BG", "Bulgaria")]
        [DataRow("BH", "Bahrain")]
        [DataRow("BI", "Burundi")]
        [DataRow("BJ", "Benin")]
        [DataRow("BL", "Saint Barthelemy")]
        [DataRow("BM", "Bermuda")]
        [DataRow("BN", "Brunei")]
        [DataRow("BO", "Bolivia")]
        [DataRow("BR", "Brazil")]
        [DataRow("BS", "Bahamas")]
        [DataRow("BT", "Bhutan")]
        [DataRow("BW", "Botswana")]
        [DataRow("BY", "Belarus")]
        [DataRow("BZ", "Belize")]
        [DataRow("CA", "Canada")]
        [DataRow("CC", "Cocos Islands")]
        [DataRow("CD", "Democratic Republic of the Congo")]
        [DataRow("CF", "Central African Republic")]
        [DataRow("CG", "Republic of the Congo")]
        [DataRow("CH", "Switzerland")]
        [DataRow("CI", "Ivory Coast")]
        [DataRow("CK", "Cook Islands")]
        [DataRow("CL", "Chile")]
        [DataRow("CM", "Cameroon")]
        [DataRow("CN", "China")]
        [DataRow("CO", "Colombia")]
        [DataRow("CR", "Costa Rica")]
        [DataRow("CU", "Cuba")]
        [DataRow("CV", "Cape Verde")]
        [DataRow("CW", "Curacao")]
        [DataRow("CX", "Christmas Island")]
        [DataRow("CY", "Cyprus")]
        [DataRow("CZ", "Czech Republic")]
        [DataRow("DE", "Germany")]
        [DataRow("DJ", "Djibouti")]
        [DataRow("DK", "Denmark")]
        [DataRow("DM", "Dominica")]
        [DataRow("DO", "Dominican Republic")]
        [DataRow("DZ", "Algeria")]
        [DataRow("EC", "Ecuador")]
        [DataRow("EE", "Estonia")]
        [DataRow("EG", "Egypt")]
        [DataRow("EH", "Western Sahara")]
        [DataRow("ER", "Eritrea")]
        [DataRow("ES", "Spain")]
        [DataRow("ET", "Ethiopia")]
        [DataRow("FI", "Finland")]
        [DataRow("FJ", "Fiji")]
        [DataRow("FK", "Falkland Islands")]
        [DataRow("FM", "Micronesia")]
        [DataRow("FO", "Faroe Islands")]
        [DataRow("FR", "France")]
        [DataRow("GA", "Gabon")]
        [DataRow("GB", "United Kingdom")]
        [DataRow("GD", "Grenada")]
        [DataRow("GE", "Georgia")]
        [DataRow("GG", "Guernsey")]
        [DataRow("GH", "Ghana")]
        [DataRow("GI", "Gibraltar")]
        [DataRow("GL", "Greenland")]
        [DataRow("GM", "Gambia")]
        [DataRow("GN", "Guinea")]
        [DataRow("GQ", "Equatorial Guinea")]
        [DataRow("GR", "Greece")]
        [DataRow("GT", "Guatemala")]
        [DataRow("GU", "Guam")]
        [DataRow("GW", "Guinea-Bissau")]
        [DataRow("GY", "Guyana")]
        [DataRow("HK", "Hong Kong")]
        [DataRow("HN", "Honduras")]
        [DataRow("HR", "Croatia")]
        [DataRow("HT", "Haiti")]
        [DataRow("HU", "Hungary")]
        [DataRow("ID", "Indonesia")]
        [DataRow("IE", "Ireland")]
        [DataRow("IL", "Israel")]
        [DataRow("IM", "Isle of Man")]
        [DataRow("IN", "India")]
        [DataRow("IO", "British Indian Ocean Territory")]
        [DataRow("IQ", "Iraq")]
        [DataRow("IR", "Iran")]
        [DataRow("IS", "Iceland")]
        [DataRow("IT", "Italy")]
        [DataRow("JE", "Jersey")]
        [DataRow("JM", "Jamaica")]
        [DataRow("JO", "Jordan")]
        [DataRow("JP", "Japan")]
        [DataRow("KE", "Kenya")]
        [DataRow("KG", "Kyrgyzstan")]
        [DataRow("KH", "Cambodia")]
        [DataRow("KI", "Kiribati")]
        [DataRow("KM", "Comoros")]
        [DataRow("KN", "Saint Kitts and Nevis")]
        [DataRow("KP", "North Korea")]
        [DataRow("KR", "South Korea")]
        [DataRow("KW", "Kuwait")]
        [DataRow("KY", "Cayman Islands")]
        [DataRow("KZ", "Kazakhstan")]
        [DataRow("LA", "Laos")]
        [DataRow("LB", "Lebanon")]
        [DataRow("LC", "Saint Lucia")]
        [DataRow("LI", "Liechtenstein")]
        [DataRow("LK", "Sri Lanka")]
        [DataRow("LR", "Liberia")]
        [DataRow("LS", "Lesotho")]
        [DataRow("LT", "Lithuania")]
        [DataRow("LU", "Luxembourg")]
        [DataRow("LV", "Latvia")]
        [DataRow("LY", "Libya")]
        [DataRow("MA", "Morocco")]
        [DataRow("MC", "Monaco")]
        [DataRow("MD", "Moldova")]
        [DataRow("ME", "Montenegro")]
        [DataRow("MF", "Saint Martin")]
        [DataRow("MG", "Madagascar")]
        [DataRow("MH", "Marshall Islands")]
        [DataRow("MK", "Macedonia")]
        [DataRow("ML", "Mali")]
        [DataRow("MM", "Myanmar")]
        [DataRow("MN", "Mongolia")]
        [DataRow("MO", "Macau")]
        [DataRow("MP", "Northern Mariana Islands")]
        [DataRow("MR", "Mauritania")]
        [DataRow("MS", "Montserrat")]
        [DataRow("MT", "Malta")]
        [DataRow("MU", "Mauritius")]
        [DataRow("MV", "Maldives")]
        [DataRow("MW", "Malawi")]
        [DataRow("MX", "Mexico")]
        [DataRow("MY", "Malaysia")]
        [DataRow("MZ", "Mozambique")]
        [DataRow("NA", "Namibia")]
        [DataRow("NC", "New Caledonia")]
        [DataRow("NE", "Niger")]
        [DataRow("NG", "Nigeria")]
        [DataRow("NI", "Nicaragua")]
        [DataRow("NL", "Netherlands")]
        [DataRow("NO", "Norway")]
        [DataRow("NP", "Nepal")]
        [DataRow("NR", "Nauru")]
        [DataRow("NU", "Niue")]
        [DataRow("NZ", "New Zealand")]
        [DataRow("OM", "Oman")]
        [DataRow("PA", "Panama")]
        [DataRow("PE", "Peru")]
        [DataRow("PF", "French Polynesia")]
        [DataRow("PG", "Papua New Guinea")]
        [DataRow("PH", "Philippines")]
        [DataRow("PK", "Pakistan")]
        [DataRow("PL", "Poland")]
        [DataRow("PM", "Saint Pierre and Miquelon")]
        [DataRow("PN", "Pitcairn")]
        [DataRow("PR", "Puerto Rico")]
        [DataRow("PS", "Palestine")]
        [DataRow("PT", "Portugal")]
        [DataRow("PW", "Palau")]
        [DataRow("PY", "Paraguay")]
        [DataRow("QA", "Qatar")]
        [DataRow("RE", "Reunion")]
        [DataRow("RO", "Romania")]
        [DataRow("RS", "Serbia")]
        [DataRow("RU", "Russia")]
        [DataRow("RW", "Rwanda")]
        [DataRow("SA", "Saudi Arabia")]
        [DataRow("SB", "Solomon Islands")]
        [DataRow("SC", "Seychelles")]
        [DataRow("SD", "Sudan")]
        [DataRow("SE", "Sweden")]
        [DataRow("SG", "Singapore")]
        [DataRow("SH", "Saint Helena")]
        [DataRow("SI", "Slovenia")]
        [DataRow("SJ", "Svalbard and Jan Mayen")]
        [DataRow("SK", "Slovakia")]
        [DataRow("SL", "Sierra Leone")]
        [DataRow("SM", "San Marino")]
        [DataRow("SN", "Senegal")]
        [DataRow("SO", "Somalia")]
        [DataRow("SR", "Suriname")]
        [DataRow("SS", "South Sudan")]
        [DataRow("ST", "Sao Tome and Principe")]
        [DataRow("SV", "El Salvador")]
        [DataRow("SX", "Sint Maarten")]
        [DataRow("SY", "Syria")]
        [DataRow("SZ", "Swaziland")]
        [DataRow("TC", "Turks and Caicos Islands")]
        [DataRow("TD", "Chad")]
        [DataRow("TG", "Togo")]
        [DataRow("TH", "Thailand")]
        [DataRow("TJ", "Tajikistan")]
        [DataRow("TK", "Tokelau")]
        [DataRow("TL", "East Timor")]
        [DataRow("TM", "Turkmenistan")]
        [DataRow("TN", "Tunisia")]
        [DataRow("TO", "Tonga")]
        [DataRow("TR", "Turkey")]
        [DataRow("TT", "Trinidad and Tobago")]
        [DataRow("TV", "Tuvalu")]
        [DataRow("TW", "Taiwan")]
        [DataRow("TZ", "Tanzania")]
        [DataRow("UA", "Ukraine")]
        [DataRow("UG", "Uganda")]
        [DataRow("US", "United States")]
        [DataRow("UY", "Uruguay")]
        [DataRow("UZ", "Uzbekistan")]
        [DataRow("VA", "Vatican")]
        [DataRow("VC", "Saint Vincent and the Grenadines")]
        [DataRow("VE", "Venezuela")]
        [DataRow("VG", "British Virgin Islands")]
        [DataRow("VI", "U.S. Virgin Islands")]
        [DataRow("VN", "Vietnam")]
        [DataRow("VU", "Vanuatu")]
        [DataRow("WF", "Wallis and Futuna")]
        [DataRow("WS", "Samoa")]
        [DataRow("XK", "Kosovo")]
        [DataRow("YE", "Yemen")]
        [DataRow("YT", "Mayotte")]
        [DataRow("ZA", "South Africa")]
        [DataRow("ZM", "Zambia")]
        [DataRow("ZW", "Zimbabwe")]
        [DataRow(null, "N/A")]
        [DataRow("", "N/A")]
        [DataRow("--", "N/A")]
        public void ConvertToFullNameTest(string countryCode, string expVal)
        {
            // Arrange

            // Act
            var actVal = CountryCode.ConvertToFullName(countryCode);

            // Assert
            Assert.AreEqual(expVal, actVal);
        }
    }
}