//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoE2NetDesktop {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SteamId {
            get {
                return ((string)(this["SteamId"]));
            }
            set {
                this["SteamId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProfileId {
            get {
                return ((int)(this["ProfileId"]));
            }
            set {
                this["ProfileId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedIdType {
            get {
                return ((int)(this["SelectedIdType"]));
            }
            set {
                this["SelectedIdType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("680, 310")]
        public global::System.Drawing.Size WindowSizeMain {
            get {
                return ((global::System.Drawing.Size)(this["WindowSizeMain"]));
            }
            set {
                this["WindowSizeMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocationMain {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocationMain"]));
            }
            set {
                this["WindowLocationMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocationHistory {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocationHistory"]));
            }
            set {
                this["WindowLocationHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 640")]
        public global::System.Drawing.Size WindowSizeHistory {
            get {
                return ((global::System.Drawing.Size)(this["WindowSizeHistory"]));
            }
            set {
                this["WindowSizeHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedIndexTabControlHistory {
            get {
                return ((int)(this["SelectedIndexTabControlHistory"]));
            }
            set {
                this["SelectedIndexTabControlHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedIndexComboBoxLeaderboard {
            get {
                return ((int)(this["SelectedIndexComboBoxLeaderboard"]));
            }
            set {
                this["SelectedIndexComboBoxLeaderboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedIndexComboBoxDataSource {
            get {
                return ((int)(this["SelectedIndexComboBoxDataSource"]));
            }
            set {
                this["SelectedIndexComboBoxDataSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal MainFormOpacityPercent {
            get {
                return ((decimal)(this["MainFormOpacityPercent"]));
            }
            set {
                this["MainFormOpacityPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#708090")]
        public string ChromaKey {
            get {
                return ((string)(this["ChromaKey"]));
            }
            set {
                this["ChromaKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainFormIsHideTitle {
            get {
                return ((bool)(this["MainFormIsHideTitle"]));
            }
            set {
                this["MainFormIsHideTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainFormIsAlwaysOnTop {
            get {
                return ((bool)(this["MainFormIsAlwaysOnTop"]));
            }
            set {
                this["MainFormIsAlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocationSettings {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocationSettings"]));
            }
            set {
                this["WindowLocationSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainFormIsTransparency {
            get {
                return ((bool)(this["MainFormIsTransparency"]));
            }
            set {
                this["MainFormIsTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawHighQuality {
            get {
                return ((bool)(this["DrawHighQuality"]));
            }
            set {
                this["DrawHighQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoReloadLastMatch {
            get {
                return ((bool)(this["IsAutoReloadLastMatch"]));
            }
            set {
                this["IsAutoReloadLastMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VisibleGameTime {
            get {
                return ((bool)(this["VisibleGameTime"]));
            }
            set {
                this["VisibleGameTime"] = value;
            }
        }
    }
}
